# Generated by Django 4.2.6 on 2023-10-29 13:48

from django.db import migrations, models
import master.models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='apikey',
            field=models.CharField(default=master.models.generate_api_key, max_length=100, unique=True),
        ),
    ]
